apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - name: book-api
          image: book-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: book-api-service
  namespace: kafka
spec:
  selector:
    app: book-api-service
  ports:
    - name: kafka-test-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
